- README.md
- TMG.EMME/TMG.EMME.Test/Copy/CopyScenarioTest.cs
- TMG.EMME/TMG.EMME.Test/Export/ExportBinaryMatrixTest.cs
- TMG.EMME/TMG.EMME.Test/Export/ExportNetworkPackageTest.cs
- TMG.EMME/TMG.EMME.Test/Import/ImportBinaryMatrixTest.cs
- TMG.EMME/TMG.EMME.Test/Import/ImportNetworkPackageTest.cs
- TMG.EMME/TMG.EMME/Copy/CopyScenario.cs
- TMG.EMME/TMG.EMME/Exceptions/EmmeToolIncompatibleError.cs
- TMG.EMME/TMG.EMME/Export/ExportBinaryMatrix.cs
- TMG.EMME/TMG.EMME/Export/ExportNetworkPackage.cs
- TMG.EMME/TMG.EMME/Import/ImportBinaryMatrix.cs
- TMG.EMME/TMG.EMME/Import/ImportNetworkPackage.cs
- TMG.EMME/TMG.EMME/LogbookLevel.cs
- TMG.EMME/TMG.EMME/ModellerBridge.py
- TMG.EMME/TMG.EMME/ModellerController.cs
- TMG.EMME/TMGToolbox2/TMGToolbox2.pyproj
- TMG.EMME/TMGToolbox2/src/Copy/copy_scenario.py
- TMG.EMME/TMGToolbox2/src/Export/export_binary_matrix.py
- TMG.EMME/TMGToolbox2/src/Export/export_network_package.py
- TMG.EMME/TMGToolbox2/src/Import/import_binary_matrix.py
- TMG.EMME/TMGToolbox2/src/Import/import_network_package.py
This commit contains the changes in order to support the run_xtmf(self, parameters) entry point.
> Updated Tool Entry Point

- TMG.EMME/TMGToolbox2/src/utilities/TMG_tool_page_builder.py
- TMG.EMME/TMGToolbox2/src/utilities/general_utilities.py
- TMG.EMME/TMGToolbox2/src/utilities/geometry.py
- TMG.EMME/TMGToolbox2/src/utilities/merge_functions.py
- TMG.EMME/TMGToolbox2/src/utilities/network_editing.py
- TMG.EMME/TMGToolbox2/src/utilities/spatial_index.py
Add utilities tools including geometry, network editing, and spatial index. Update the branding name to Toolbox 2.
> Add utilities and Update branding

- TMG.EMME/TMG.EMME.Test/Convert/ConvertGTFSStopsToShapefileTest.cs
- TMG.EMME/TMG.EMME.Test/Convert/RotateNetworkTest.cs
- TMG.EMME/TMG.EMME/Convert/ConvertGTFSStopsToShapefile.cs
- TMG.EMME/TMG.EMME/Convert/RotateNetwork.cs
- TMG.EMME/TMG.EMME/ModellerBridge.py
- TMG.EMME/TMGToolbox2/src/Convert/convert_gtfs_stops_to_shapefile.py
- TMG.EMME/TMGToolbox2/src/Convert/rotate_network.py
> Rotate Network

- TMG.EMME/TMG.EMME.Test/Assign/AssignBoardingPenaltyTest.cs
- TMG.EMME/TMG.EMME.Test/Assign/AssignTrafficTest.cs
- TMG.EMME/TMG.EMME.Test/Assign/AssignTransitTest.cs
- TMG.EMME/TMG.EMME.Test/Calculate/CalculateNetworkAttributeTest.cs
- TMG.EMME/TMG.EMME.Test/Convert/ConvertGTFSStopsToShapefileTest.cs
- TMG.EMME/TMG.EMME.Test/Convert/ReverseTransitLinesTest.cs
- TMG.EMME/TMG.EMME.Test/Convert/RotateNetworkTest.cs
- TMG.EMME/TMG.EMME.Test/Export/ExportBoardingAndAlightingTest.cs
- TMG.EMME/TMG.EMME.Test/Export/ExportNetworkShapefileTest.cs
- TMG.EMME/TMG.EMME.Test/Helper.cs
- TMG.EMME/TMG.EMME.Test/Import/ImportNetworkPackageTest.cs
- TMG.EMME/TMG.EMME/Assign/AssignBoardingPenalty.cs
- TMG.EMME/TMG.EMME/Assign/AssignTraffic.cs
- TMG.EMME/TMG.EMME/Calculate/CalculateNetworkAttribute.cs
- TMG.EMME/TMG.EMME/Convert/ConvertGTFSStopsToShapefile.cs
- TMG.EMME/TMG.EMME/Convert/ReverseTransitLines.cs
- TMG.EMME/TMG.EMME/Convert/RotateNetwork.cs
- TMG.EMME/TMG.EMME/Export/ExportNetworkShapefile.cs
- TMG.EMME/TMGToolbox2/src/Assign/assign_boarding_penalty.py
- TMG.EMME/TMGToolbox2/src/Assign/assign_traffic.py
- TMG.EMME/TMGToolbox2/src/Calculate/calculate_network_attribute.py
- TMG.EMME/TMGToolbox2/src/Convert/convert_gtfs_stops_to_shapefile.py
- TMG.EMME/TMGToolbox2/src/Convert/reverse_transit_lines.py
- TMG.EMME/TMGToolbox2/src/Convert/rotate_network.py
- TMG.EMME/TMGToolbox2/src/Export/export_network_shapefile.py
This update does not include any of the recent updates in transit assignment tools
> Update and test none transit assignment tools

- TMG.EMME/TMG.EMME.Test/Assign/AssignTrafficTest.cs
- TMG.EMME/TMG.EMME/Assign/AssignTraffic.cs
- TMG.EMME/TMGToolbox2/src/Assign/assign_traffic.py
Added a new parameter to give the ranges of TTFs that should be used when applying background transit congestion during the road assignment.
> Mixed-use Transit TTFs for Road Assignment.

- TMG.EMME/TMG.EMME.Test/Generate/GenerateTimePeriodNetworksTest.cs
- TMG.EMME/TMG.EMME/Generate/GenerateTimePeriodNetworks.cs
- TMG.EMME/TMGToolbox2/src/Generate/generate_time_period_networks.py
- TMG.EMME/TMGToolbox2/src/utilities/general_utilities.py
- TMG.EMME/TMGToolbox2/src/utilities/network_editing.py
Closes #112 
Closes #113 
Closes #110
> Prorate transit speed

- TMG.EMME/TMG.EMME/Generate/GenerateTimePeriodNetworks.cs
> adjusted descriptions

- TMG.EMME/TMG.EMME.Test/Generate/GenerateTimePeriodNetworksTest.cs
- TMG.EMME/TMG.EMME/Generate/GenerateTimePeriodNetworks.cs
- TMG.EMME/TMGToolbox2/src/Generate/generate_time_period_networks.py
> Rewrite aggregate type

- TMG.EMME/TMGToolbox2/src/Copy/copy_scenario.py
> adjusted copy scenario

- TMG.EMME/TMGToolbox2/src/Calculate/calculate_network_attribute.py
> removed magic numbers

- TMG.EMME/TMG.EMME.Test/Export/ExportBinaryMatrixTest.cs
- TMG.EMME/TMG.EMME/Export/ExportBinaryMatrix.cs
- TMG.EMME/TMGToolbox2/src/Export/export_binary_matrix.py
- TMG.EMME/TMGToolbox2/src/Import/import_binary_matrix.py
- TMG.EMME/TMGToolbox2/src/utilities/general_utilities.py
> Improve import export binary matrix

- TMG.EMME/TMG.EMME.Test/Helper.cs
- TMG.EMME/TMG.EMME.Test/Import/ImportBinaryMatrixTest.cs
- TMG.EMME/TMG.EMME/Import/ImportBinaryMatrix.cs
- TMG.EMME/TMGToolbox2/src/Import/import_binary_matrix.py
> Fix import bin matrix

- TMG.EMME/TMG.EMME.Test/Export/ExportBinaryMatrixTest.cs
- TMG.EMME/TMG.EMME/Export/ExportBinaryMatrix.cs
> convert matrix type to enum

- TMG.EMME/TMG.EMME.Test/Export/ExportNetworkPackageTest.cs
- TMG.EMME/TMG.EMME/Export/ExportNetworkPackage.cs
- TMG.EMME/TMGToolbox2/src/Export/export_network_package.py
> added new parameters and removed page builder

- TMG.EMME/TMG.EMME.Test/Filter/FilterGTFSForServiceIdAndRoutesTest.cs
- TMG.EMME/TMG.EMME/Filter/FilterGTFSForServiceIdAndRoutes.cs
- TMG.EMME/TMGToolbox2/src/Filter/filter_gtfs_for_service_id_and_routes.py
> Clean gtfs fix

- TMG.EMME/TMG.EMME.Test/Convert/ReverseTransitLinesTest.cs
- TMG.EMME/TMG.EMME.Test/Convert/RotateNetworkTest.cs
- TMG.EMME/TMGToolbox2/src/Convert/reverse_transit_lines.py
> Fix reverse network

- TMG.EMME/TMG.EMME.Test/Import/ImportNetworkPackageTest.cs
- TMG.EMME/TMG.EMME/Import/ImportNetworkPackage.cs
- TMG.EMME/TMGToolbox2/src/Import/import_network_package.py
> Import network package fix

- TMG.EMME/TMG.EMME.Test/Convert/ConvertGTFSStopsToShapefileTest.cs
- TMG.EMME/TMG.EMME/Convert/ConvertGTFSStopsToShapefile.cs
- TMG.EMME/TMGToolbox2/src/Convert/convert_gtfs_stops_to_shapefile.py
> improved code base for convert gtfs stops to shapefile

- TMG.EMME/TMG.EMME.Test/Export/ExportSubareaTest.cs
- TMG.EMME/TMG.EMME/Export/ExportSubarea.cs
- TMG.EMME/TMGToolbox2/src/Export/export_subarea.py
> Subarea gate info

- TMG.EMME/TMG.EMME.Test/Export/ExportSubareaTest.cs
- TMG.EMME/TMG.EMME/Export/ExportSubarea.cs
- TMG.EMME/TMGToolbox2/src/Export/export_subarea.py
> Create node attribute

- TMG.EMME/TMG.EMME.Test/Export/ExportSubareaTest.cs
- TMG.EMME/TMG.EMME/Export/ExportSubarea.cs
- TMG.EMME/TMGToolbox2/src/Export/export_subarea.py
> Fixed subarea tool

- TMG.EMME/TMG.EMME.Test/Export/ExportMatchingEmmeNodesForGtfsStopsTest.cs
- TMG.EMME/TMGToolbox2/src/Export/export_matching_emme_nodes_for_gtfs_stops.py
> modified the export matching node tool

- TMG.EMME/TMG.EMME.Test/Import/ImportTransitLinesFromGtfsTest.cs
- TMG.EMME/TMG.EMME/Import/ImportTransitLinesFromGtfs.cs
- TMG.EMME/TMGToolbox2/src/Export/export_matching_emme_nodes_for_gtfs_stops.py
- TMG.EMME/TMGToolbox2/src/Import/import_transit_lines_from_gtfs.py
> Fix generate transit lines from gtfs
